# Generated by Django 5.1.2 on 2024-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_category_alter_income_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
