# Generated by Django 5.1.2 on 2024-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
